## 1. Import libraries and dependencies

In [1]:
from src.preprocess.preprocess import Preprocess
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2024-05-18 16:51:41.583004: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-18 16:51:41.585602: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-18 16:51:41.621301: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-18 16:51:42.277607: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


/home/hubert/Workspace/Python/ML Project/languages
{'cs': '/home/hubert/Workspace/Python/ML Project/languages/cs', 'lt': '/home/hubert/Workspace/Python/ML Project/languages/lt', 'pl': '/home/hubert/Workspace/Python/ML Project/languages/pl'}
{'cs': '/home/hubert/Workspace/Python/ML Project/languages/cs/validated.tsv', 'lt': '/home/hubert/Workspace/Python/ML Project/languages/lt/validated.tsv', 'pl': '/home/hubert/Workspace/Python/ML Project/languages/pl/validated.tsv'}
{'cs': '/home/hubert/Workspace/Python/ML Project/languages/cs/clip_durations.tsv', 'lt': '/home/hubert/Workspace/Python/ML Project/languages/lt/clip_durations.tsv', 'pl': '/home/hubert/Workspace/Python/ML Project/languages/pl/clip_durations.tsv'}


## 2. Preprocess audio

In [2]:
train_dataset, val_dataset, test_dataset = Preprocess().preprocess()

PROCESSED LANGUAGES: cs


2024-05-18 16:51:42.913879: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2024-05-18 16:51:42.913903: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:134] retrieving CUDA diagnostic information for host: Ubuntu
2024-05-18 16:51:42.913910: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:141] hostname: Ubuntu
2024-05-18 16:51:42.913989: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:165] libcuda reported version is: 550.54.15
2024-05-18 16:51:42.914008: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:169] kernel reported version is: 535.171.4
2024-05-18 16:51:42.914014: E external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:251] kernel version 535.171.4 does not match DSO version 550.54.15 -- cannot find working devices in this configuration


---AUDIO META INFO DONE cs---
---SET SPLIT DONE 0 cs---


2024-05-18 16:51:43.727556: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA


---DATASET DONE 0 cs---
---SET SPLIT DONE 1 cs---


2024-05-18 16:51:45.714701: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


---DATASET DONE 1 cs---
PROCESSED LANGUAGES: lt
---AUDIO META INFO DONE lt---
---SET SPLIT DONE 0 lt---


2024-05-18 16:51:47.696140: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


---DATASET DONE 0 lt---
---SET SPLIT DONE 1 lt---


2024-05-18 16:51:49.702392: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


---DATASET DONE 1 lt---
PROCESSED LANGUAGES: pl


2024-05-18 16:51:51.444517: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


---AUDIO META INFO DONE pl---
---SET SPLIT DONE 0 pl---
---DATASET DONE 0 pl---
---SET SPLIT DONE 1 pl---


2024-05-18 16:51:55.698017: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


---DATASET DONE 1 pl---


2024-05-18 16:51:57.956704: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


SHUFFLE
BATCHING


In [3]:
counter = 0
for batch, label in train_dataset:
        print(batch.shape)
        for sample in batch:
                print(sample)
                counter += 1
print(counter)


(16, 1991, 257, 1)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]], shape=(1991, 257, 1), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]], shape=(1991, 257, 1), dtype=float32)
tf.Tensor(
[[[4.41199839e-02]
  [1.01500206e-01]
  [5.28916121e-01]
  ...
  [1.53947167e-05]
  [1.42159188e-05]
  [1.46031380e-05]]

 [[2.51665354e-01]
  [1.69852078e-01]
  [4.81477082e-01]
  ...
  [3.27647795e-05]
  [9.50641061e-06]
  [9.83476639e-06]]

 [[2.66718566e-0

2024-05-18 16:51:58.736986: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [4]:
counter = 0
for batch, label in val_dataset:
        print(batch.shape)
        for sample in batch:
                print(sample)
                counter += 1
print(counter)

(16, 1991, 257, 1)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]], shape=(1991, 257, 1), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]], shape=(1991, 257, 1), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0

2024-05-18 16:51:58.937990: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


tf.Tensor(
[[[1.46540347e-04]
  [2.24737669e-04]
  [1.07184642e-04]
  ...
  [2.77541221e-06]
  [2.24025507e-06]
  [7.73929060e-07]]

 [[1.17153395e-04]
  [2.15312073e-04]
  [3.50900053e-04]
  ...
  [3.51085691e-06]
  [2.54326528e-06]
  [3.37371603e-06]]

 [[1.46348902e-04]
  [9.54515563e-05]
  [4.29158914e-04]
  ...
  [1.41852036e-06]
  [9.87682483e-07]
  [7.39237294e-09]]

 ...

 [[3.69960326e-05]
  [7.13971749e-05]
  [1.70732805e-04]
  ...
  [1.01913456e-05]
  [3.66573954e-06]
  [1.52428402e-06]]

 [[6.43477761e-05]
  [5.89593110e-05]
  [1.12935792e-04]
  ...
  [8.73758472e-06]
  [2.10643839e-06]
  [3.98584234e-07]]

 [[4.12639856e-05]
  [5.58636093e-05]
  [7.46844598e-05]
  ...
  [7.36331276e-06]
  [2.67536916e-06]
  [2.91729521e-07]]], shape=(1991, 257, 1), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.

In [5]:
counter = 0
for batch, label in test_dataset:
        print(batch.shape)
        for sample in batch:
                print(sample)
                counter += 1
print(counter)

(16, 1991, 257, 1)
tf.Tensor(
[[[4.2555109e-01]
  [3.1454864e-01]
  [2.8054118e-01]
  ...
  [1.6139385e-05]
  [6.9432258e-06]
  [6.9439411e-06]]

 [[5.9424388e-01]
  [5.1901668e-01]
  [4.4244039e-01]
  ...
  [1.1358596e-05]
  [5.1851971e-06]
  [7.1823597e-06]]

 [[8.1650561e-01]
  [7.1526378e-01]
  [4.7778907e-01]
  ...
  [5.9282479e-06]
  [4.0074983e-06]
  [2.3245811e-06]]

 ...

 [[1.0821798e+00]
  [8.7685555e-01]
  [4.8466724e-01]
  ...
  [1.3566656e-06]
  [8.7041150e-07]
  [1.4901161e-06]]

 [[1.1963413e+00]
  [1.0063360e+00]
  [5.9916234e-01]
  ...
  [8.8671300e-07]
  [2.1073424e-07]
  [4.1723251e-07]]

 [[1.1968709e+00]
  [1.0336171e+00]
  [6.4635420e-01]
  ...
  [1.6542973e-06]
  [8.0975161e-07]
  [1.3113022e-06]]], shape=(1991, 257, 1), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]

2024-05-18 16:51:59.125734: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [6]:
train_dataset = train_dataset.batch(32)

In [7]:
        samples, labels = train_dataset.as_numpy_iterator().next()
        print()
        print(samples.shape, labels.shape)
        samples, labels = val_dataset.as_numpy_iterator().next()
        print(samples.shape, labels.shape)
        samples, labels = test_dataset.as_numpy_iterator().next()
        print(samples.shape, labels.shape)

2024-05-18 16:51:59.594879: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 392975616 exceeds 10% of free system memory.
2024-05-18 16:51:59.648251: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Cannot batch tensors with different shapes in component 0. First element had shape [16,1991,257,1] and element 11 had shape [4,1991,257,1].


InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Cannot batch tensors with different shapes in component 0. First element had shape [16,1991,257,1] and element 11 had shape [4,1991,257,1]. [Op:IteratorGetNext] name: 